source 'https://rubygems.org'
ruby '2.0.0'

gem 'dalli'
gem 'acts-as-taggable-on'
gem 'airbrake'
gem 'bourbon'
gem 'choices'
gem 'daemons'
gem 'delayed_job'
gem 'delayed_job_active_record'
gem 'delayed_job_web'
gem 'devise'
gem 'devise-encryptable'
gem 'draper'
gem 'dynamic_form'
gem 'foreman'
gem 'sass-rails', '~> 4.0.2'
gem 'compass-rails', '~> 1.1.0'
gem 'bootstrap-sass'
gem 'pivotal-sass'
gem 'haml-rails'
gem 'jquery-rails'
gem 'mime-types'
gem 'nokogiri'
gem 'omniauth'
gem 'omniauth-google-oauth2'
gem 'pivotal-tracker'
gem 'rails', '4.0.4'
gem 'rake'
gem 'xpath'
gem 'whenever', require: false
gem 'rails-backbone'
gem 'coffee-rails', '~> 4.0.0'
gem 'eco'
gem 'pg'
gem 'eventmachine'
gem 'em-http-request'
gem 'newrelic_rpm'
gem 'hashie'
gem 'unicorn'
gem 'uglifier', '>= 1.3.0'
gem 'clockwork'
gem 'jbuilder'
gem 'ruby-openid', '~>2.5.0'

group :production do
  gem 'rails_12factor'
  gem 'therubyracer'
end

group :test do
  gem 'headless'
  gem 'vcr', '2.9.0'
  gem 'fakeweb'
  gem 'sqlite3'
end

# NOTE: anything that will not work in travis should be here
group :development do
  gem 'awesome_print'
  gem 'heroku_san'
  gem 'guard-livereload'
  gem 'rb-fsevent', '~> 0.9.1'
  gem 'ruby-prof'
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'better_errors'
  gem 'binding_of_caller'
end

group :test, :development do
  gem 'launchy'
  gem 'jshint_on_rails'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'shoulda-matchers'
  gem 'capybara'
  gem 'jasmine', github: 'pivotal/jasmine-gem'
  gem 'jasmine-rails'
  gem 'selenium-webdriver', '>= 2.25.0' # NOTE: selenium-webdriver >= 2.25.0 is needed for the latest Firefox
  gem 'factory_girl_rails'
  gem 'ffaker'
  gem 'guard-coffeescript'
  gem 'database_cleaner'
  gem 'capybara-webkit'
  gem 'pry-nav'
  gem 'pry-rails'
  gem 'pry'
  gem 'vagrant'
  gem 'timecop'
  gem 'did_you_mean'
end
