#!/bin/bash
#
# Copyright (c) 2006 Bradley Taylor, bradley@railsmachine.com
#
# mongrel_cluster       Startup script for Mongrel clusters.
#
# chkconfig: - 85 15
# description: mongrel_cluster manages multiple Mongrel processes for use \
#              behind a load balancer.
#

#!/bin/bash
#


CONF_DIRS=$2
RETVAL=0
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin

#stat "$2" >>/dev/null ||
#{
#  echo "Usage: mongrel_cluster {start|stop|restart} {paths/to/mongrel/config}"
#  exit 1;
#} &&
#{
#  echo "Using config dir: $2";
#}

case "$1" in
    start)
      for dir in $CONF_DIRS; do
        mongrel_cluster_ctl start --clean -c $dir
        RETVAL=$RETVAL||$?
      done
  ;;
    stop)
      for dir in $CONF_DIRS; do
        mongrel_cluster_ctl stop --clean -c $dir
        RETVAL=$RETVAL||$?
      done
  ;;
    restart)
      for dir in $CONF_DIRS; do
        mongrel_cluster_ctl stop --clean -c $dir
        mongrel_cluster_ctl start --clean -c $dir
        RETVAL=$?
      done
  ;;
    *)
      echo "Usage: mongrel_cluster {start|stop|restart} {path/to/mongrel/config}"
      exit 1
  ;;
esac

exit $RETVAL
